In [1]:
!python -c "import torch;print(torch.cuda.can_device_access_peer(0, 1))"

True


## gpu to gpu vs. gpu to cpu to gpu

- https://github.com/pytorch/pytorch/issues/84803

In [11]:
import torch
torch.__version__

'2.0.1'

In [12]:
torch.version.cuda

'11.8'

In [13]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0


### gpu => gpu

In [3]:
import torch
x = torch.tensor([1], device=0)
x

tensor([1], device='cuda:0')

In [4]:
x.to(1)

tensor([0], device='cuda:1')

In [5]:
x = torch.tensor([1.0, 2.0], device=0)
x.to(1)

tensor([0., 0.], device='cuda:1')

### gpu => cpu => gpu

In [7]:
x

tensor([1., 2.], device='cuda:0')

In [6]:
x.to('cpu').to(1)

tensor([1., 2.], device='cuda:1')